apiVersion: apps/v1
kind: Deployment
metadata:
  name: sroom-prt01-scanner
  namespace: sroom-prt01-scanner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sroom-prt01-scanner
  template:
    metadata:
      labels:
        app: sroom-prt01-scanner 
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [{
            "name": "ens20-net",
            "namespace": "sroom-prt01-scanner",
            "mac": "02:fd:20:30:40:01"
          }]
    spec:
      containers:        
        - name: sroom-prt01-scanner
          image: ghcr.io/jhoareaumarion/brotherscannerdocker:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: cm
            - secretRef:
                name: secrets
          ports:
            - containerPort: 33555            
            - containerPort: 54925
              protocol: UDP
              name: scanner-udp
            - containerPort: 54921
              protocol: TCP
              name: scanner-tcp
            - containerPort: 161
              protocol: UDP
              name: snmp-udp