apiVersion: apps/v1
kind: Deployment
metadata:
  name: sroom-prt01-scanner
  namespace: sroom-prt01-scanner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sroom-prt01-scanner
  template:
    metadata:
      labels:
        app: sroom-prt01-scanner
    spec:
      containers:        
        - name: sroom-prt01-scanner
          image: ghcr.io/drakkan/sroom-prt01-scanner:v1.1.1
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: cm
            - secretRef:
                name: secrets
          ports:
            - containerPort: 33555            
            - containerPort: 54925
              protocol: UDP
              name: scanner-udp
            - containerPort: 54921
              protocol: TCP
              name: scanner-tcp
            - containerPort: 161
              protocol: UDP
              name: snmp-udp

          volumeMounts:
            - name: sroom-prt01-scanner-home-volume
              mountPath: /var/lib/sroom-prt01-scanner
            - name: sroom-prt01-scanner-data-volume
              mountPath: /srv/sroom-prt01-scanner
            - name: paperless-consume-volume
              mountPath: /mnt/paperless-consume
      volumes:
        - name: sroom-prt01-scanner-home-volume
          persistentVolumeClaim:
            claimName: sroom-prt01-scanner-home-pvc
        - name: sroom-prt01-scanner-data-volume
          persistentVolumeClaim:
            claimName: sroom-prt01-scanner-data-pvc        
        - name: paperless-consume-volume         
          persistentVolumeClaim:
            claimName: paperless-consume-pvc