apiVersion: v1
kind: Service
metadata:
  name: sroom-prt01-scanner
  namespace: sroom-prt01-scanner
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 33555
    targetPort: 33555
  selector:
    app: sroom-prt01-scanner
