apiVersion: v1
kind: Service
metadata:
  name: paperless-web
  namespace: paperless-ngx
spec:
  selector:
    app: paperless-web
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP