apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: ingress-gateway
  namespace: cluster-gateway  # Dedicated namespace for the gateway
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    k8s.v1.cni.cncf.io/networks: vlan50-ens18
spec:
  gatewayClassName: haproxy
  listeners:
  ###
  # ACTUAL BUDGET
  ###
  - name: http
    hostname: "actual-budget.hoareau-marion.eu"
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            gateway-access: actual-budget
  - name: https
    hostname: "actual-budget.hoareau-marion.eu"
    port: 443  
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
        - name: actual-budget-hoareau-marion-eu-tls
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            gateway-access: actual-budget
  ###
  # CODE SERVER
  ###
  - name: code-server-http
    hostname: "code-server.hoareau-marion.eu"
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            gateway-access: code-server

  - name: code-server-https
    hostname: "code-server.hoareau-marion.eu"
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
        - name: code-server-hoareau-marion-eu-tls   # Secret must exist in gateway’s namespace
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            gateway-access: code-server
  ###
  # RYOT
  ###
  - name: ryot-http
    hostname: "ryot.hoareau-marion.eu"
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            gateway-access: ryot

  - name: ryot-https
    hostname: "ryot.hoareau-marion.eu"
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
        - name: ryot-hoareau-marion-eu-tls   # Secret must exist in gateway’s namespace
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            gateway-access: ryot  
  ###
  # UPTIME KUMA
  ###
  - name: uptime-kuma-http
    hostname: "uptime-kuma.hoareau-marion.eu"
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            gateway-access: uptime-kuma

  - name: uptime-kuma-https
    hostname: "uptime-kuma.hoareau-marion.eu"
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
        - name: uptime-kuma-hoareau-marion-eu-tls   # Secret must exist in gateway’s namespace
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            gateway-access: uptime-kuma
  ###
  # PAPERLESS NGX
  ###
  - name: paperless-ngx-http
    hostname: "paperless-ngx.hoareau-marion.eu"
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            gateway-access: paperless-ngx

  - name: paperless-ngx-https
    hostname: "paperless-ngx.hoareau-marion.eu"
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
        - name: paperless-ngx-hoareau-marion-eu-tls   # Secret must exist in gateway’s namespace
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            gateway-access: paperless-ngx  
  ###
  # SFTPGO
  ###
  - name: sftpgo-http
    hostname: "sftpgo.hoareau-marion.eu"
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            gateway-access: sftpgo
  - name: sftpgo-https
    hostname: "sftpgo.hoareau-marion.eu"
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
      - name: sftpgo-hoareau-marion-eu-tls  # Create this TLS secret
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            gateway-access: sftpgo  
  ###
  # BROTHER SCANNER
  ###
  - name: sroom-prt01-scanner-http
    hostname: "sroom-prt01-scanner.hoareau-marion.eu"
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            gateway-access: sroom-prt01-scanner
  - name: sroom-prt01-scanner-https
    hostname: "sroom-prt01-scanner.hoareau-marion.eu"
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
      - name: sroom-prt01-scanner-hoareau-marion-eu-tls  # Create this TLS secret
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            gateway-access: sroom-prt01-scanner