apiVersion: cilium.io/v2alpha1
kind: CiliumNodeConfig
metadata:
  name: vlan50-gateway-nodes
spec:
  nodeSelector:
    matchLabels:
      egress: "50"
  matchServices:
  - matchLabels:
      gateway.networking.k8s.io/gateway-name: ingress-gateway