apiVersion: v1
kind: ConfigMap
metadata:
  name: ryot-cm
  namespace: ryot
data:
  TZ: "Europe/Paris"
  POSTGRES_DB: "ryot"
  POSTGRES_USER: "ryot"
  FRONTEND_OIDC_BUTTON_LABEL: "Connect with Keycloak"
  DISABLE_TELEMETRY: "true"