apiVersion: apps/v1
kind: Deployment
metadata:
  name: ryot
  namespace: ryot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ryot
  template:
    metadata:
      labels:
        app: ryot
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          envFrom:
            - configMapRef:
                name: database-cm
            - secretRef:
                name: database-ryot-secret
          env:
            - name: TZ
              value: "Europe/Paris"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
        - name: ryot
          image: ignisda/ryot:v9.5.1
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: ryot-cm
            - secretRef:
                name: ryot-secrets
          env:
            - name: TZ
              value: "Europe/Paris"
          ports:
            - containerPort: 8000
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: ryot-database-pvc